import "./globals.css";
import { Sora } from "next/font/google";
import { TrpcProvider } from "@/utils/trpc-provider";
import AuthProvider from "@/utils/AuthProvider";
const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "SultonBlanc",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} page relative bg-site bg-cover bg-no-repeat text-white`}
      >
        <TrpcProvider>
          <AuthProvider>{children}</AuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
};

export default RootLayout;
