import "./globals.css";
import { Sora } from "next/font/google";
import { TrpcProvider } from "@/utils/trpc-provider";
import AuthProvider from "@/utils/AuthProvider";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Sultonoir",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/png+xml"
          href="/AI.png"
        />
      </head>
      <body
        className={`${inter.className} relative bg-background text-primary`}
      >
        <TrpcProvider>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
            >
              {children}
            </ThemeProvider>
          </AuthProvider>
        </TrpcProvider>
      </body>
    </html>
  );
};

export default RootLayout;
